### PR TITLE
fix(Shapefile): Ignore TS7053 in parseRow function

### LINKED ISSUE #2263: TS7053 in parse-dbf.ts
Hi,

`parseRow` function in `parse-dbf.ts` seems to have a TS error.

```
@loaders.gl/shapefile/src/lib/parsers/parse-dbf.ts(299,5): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{}'.
```

A quick & dirty fix could be to add a `@ts-ignore` before `out[field.name] = parseField(text, field.dataType);`

https://github.com/visgl/loaders.gl/blob/master/modules/shapefile/src/lib/parsers/parse-dbf.ts#L299

### PR DESCRIPTION
**Pull request by Ngopimas**
Ignore TS7053 error in `parseRow` function to fix #2263.

### CODE REVIEW

**Comment by kylebarron** [comment]
You might be using a different typescript version as we are, since our lint passes this line. Regardless, a better fix would be to type the `out` object instead of ignoring that line entirely

**Comment by Ngopimas** [comment]
You are right. My initial fix was similar to how TS errors are handled in the parseState function, but still not a good way to handle it. PR updated according to your comment.

File: modules/shapefile/src/lib/parsers/parse-dbf.ts [hunk 1]
```diff
@@ -290,13 +290,14 @@ function parseRow(
   fields: DBFField[],
   textDecoder: TextDecoder
 ): {[key: string]: any} {
-  const out = {};
+  const out = {} as {
+		[key: string]: string | number | boolean | null;
+	};
```
Comment (kylebarron) [inline modules/shapefile/src/lib/parsers/parse-dbf.ts:295]: Could use use spaces, not tabs, for indentation to be consistent with the rest of the codebase? Otherwise looks good

File: modules/shapefile/src/lib/parsers/parse-dbf.ts [hunk 2]
```diff
@@ -290,7 +290,7 @@ function parseRow(
   fields: DBFField[],
   textDecoder: TextDecoder
 ): {[key: string]: any} {
-  const out = {};
+  const out = {} as {[key: string]: string | number | boolean | null};
```
Comment (ibgreen) [inline modules/shapefile/src/lib/parsers/parse-dbf.ts:293]: Does this work? E.g. typing the declaration instead of casting the initialization value?
```suggestion
  const out: {[key: string]: string | number | boolean | null} = {};
```

Comment (Ngopimas) [reply modules/shapefile/src/lib/parsers/parse-dbf.ts]: It does, I update the code accordingly.

**Review by kylebarron — APPROVED** [review]

**Review by ibgreen — APPROVED** [review]

**Comment by ibgreen** [comment]
@belom88 seems test fail in Tile3D traversal can you take a look?

**Review by ibgreen — APPROVED** [review]
